name: CI
 
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'app/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'app/**'
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'
 
      - name: Install dependencies
        run: npm install
 
      - name: Run lint
        run: npm run lint
 
  release:
    needs: build
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'
 
      - name: Install dependencies
        run: npm install
 
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          NPM_TOKEN: ${{ secrets.SEMECANTANPM }}
        run: npx semantic-release